apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-bus-postgres-init
data:
  init.sql: |-
{{ .Files.Get "files/postgres/init.sql" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-bus-clickhouse-init
data:
  init.sql: |-
{{ .Files.Get "files/clickhouse/init.sql" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-bus-prometheus-config
data:
  prometheus.yml: |-
{{ .Files.Get "files/prometheus/prometheus.yml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-bus-debezium-connectors
data:
{{- range $path, $_ := .Files.Glob "files/debezium/*.json" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-bus-clickhouse-sink-connectors
data:
{{- range $path, $_ := .Files.Glob "files/clickhouse-sink/*.json" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-bus-debezium-registrar-script
data:
  register-connectors.sh: |-
{{ .Files.Get "files/debezium/register-connectors.sh" | indent 4 }}
