apiVersion: v1
kind: Secret
metadata:
  name: integration-bus-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  clickhouse-password: {{ .Values.secrets.clickhousePassword | quote }}
  masking-hmac-salt: {{ .Values.secrets.maskingHmacSalt | quote }}
