global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'processing-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['integration-bus-processing-api:5201']

  - job_name: 'saga-orchestrator'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['integration-bus-saga-orchestrator-service:6001']

  - job_name: 'account-balance'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['integration-bus-account-balance-service:6002']

  - job_name: 'compliance'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['integration-bus-compliance-service:6003']

  - job_name: 'core-ledger'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['integration-bus-core-ledger-service:6004']
