// <auto-generated />
using System;
using IntegrationBus.AccountBalance.Service.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegrationBus.AccountBalance.Service.Migrations
{
    [DbContext(typeof(BalanceDbContext))]
    [Migration("20260729184544_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegrationBus.AccountBalance.Service.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("IntegrationBus.AccountBalance.Service.Entities.AccountJournalEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AmountDelta")
                        .HasColumnType("numeric");

                    b.Property<int>("EntryType")
                        .HasColumnType("integer");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceAccountId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("IntegrationBus.AccountBalance.Service.Entities.AccountSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SnapshotBalance")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
