<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-IntegrationBus.SagaOrchestrator.Service-4b34c939-964e-4b8e-97ee-3ff9d3227188</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.10" />
    <PackageReference Include="MassTransit.Kafka" Version="8.5.10" />
    <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.10" />
    <PackageReference Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Kafka" Version="9.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Span" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Grafana.Loki" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contracts\IntegrationBus.AccountBalance.Contracts\IntegrationBus.AccountBalance.Contracts.csproj" />
    <ProjectReference Include="..\..\Contracts\IntegrationBus.Compliance.Contracts\IntegrationBus.Compliance.Contracts.csproj" />
    <ProjectReference Include="..\..\Contracts\IntegrationBus.CoreLedger.Contracts\IntegrationBus.CoreLedger.Contracts.csproj" />
    <ProjectReference Include="..\..\Contracts\IntegrationBus.SagaOrchestrator.Contracts\IntegrationBus.SagaOrchestrator.Contracts.csproj" />
    <ProjectReference Include="..\..\Libraries\IntegrationBus.Shared\IntegrationBus.Shared.csproj" />
  </ItemGroup>
</Project>
